language: cpp

dist: bionic
os: linux

jobs:
  include:
    #######################
    - name: "Release Build"
      script:
        - cd src
        - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_TYPE=Gcc
        - cmake --build build
        - ./build/oatest/oatest
        - ./build/oalhstest/oalhstest
    ########################
    - name: "Valgrind Build"
      addons:
        apt:
          packages:
            - valgrind
      script:
        - cd src
        - cmake . -Bdebugbuild -DCMAKE_BUILD_TYPE=Debug -DBUILD_TYPE=Gcc
        - cmake --build debugbuild
        - valgrind --leak-check=full --error-exitcode=1 --track-origins=yes ./debugbuild/oatest/oatest
        - valgrind --leak-check=full --error-exitcode=1 --track-origins=yes ./debugbuild/oalhstest/oalhstest
    ###################
    - name: "gcc-san Build"
      script:
        - cd src
        - cmake . -Bgccsanbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_TYPE=Gcc-san
        - cmake --build gccsanbuild
        - ./gccsanbuild/oatest/oatest
        - ./gccsanbuild/oalhstest/oalhstest
    #####################
    - name: "clang build"
      addons:
        apt:
          packages:
            - clang
            - llvm
      script:
        - cd src
        - export CC=clang
        - export CXX=clang++
        - cmake . -Bclangbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_TYPE=Clang -D_CMAKE_TOOLCHAIN_PREFIX='llvm-'
        - cmake --build clangbuild
        - ./clangbuild/oatest/oatest
        - ./clangbuild/oalhstest/oalhstest
    #########################
    - name: "clang-san build"
      addons:
        apt:
          packages:
            - clang
            - llvm
      script:
        - cd src
        - export CC=clang
        - export CXX=clang++
        - cmake . -Bclangsanbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_TYPE=Clang-san -D_CMAKE_TOOLCHAIN_PREFIX='llvm-'
        - cmake --build clangsanbuild
        - ./clangsanbuild/oatest/oatest
        - ./clangsanbuild/oalhstest/oalhstest
    ########################
    - name: "coverage build"
      addons:
        apt:
          packages:
            - lcov
      script:
        - cd src
        - cmake . -Bcoveragebuild -DCMAKE_BUILD_TYPE=Release -DBUILD_TYPE=Coverage
        - cmake --build coveragebuild
        - ./coveragebuild/oatest/oatest
        - ./coveragebuild/oalhstest/oalhstest
      after_success:
        - cd coveragebuild
        - lcov --directory oatest --directory oalhstest --capture --output-file oatest.info
        - lcov --remove oatest.info 'oatest/*' 'oalhstest/*' '/usr/*' --output-file oatest.clean.info
        - lcov --list oatest.clean.info
        - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

