language: c++

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - lcov
      - r-base
      - r-base-dev

install:
  - sudo R --slave --vanilla -e "install.packages('Rcpp', repos='http://cran.case.edu')"

script:
  - cd oa_nb
  - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release # Test release build options
  - cmake --build build
  - ./build/oatest/oatest
  - ./build/oalhstest/oalhstest
  - cmake . -Bcoveragebuild -DCMAKE_BUILD_TYPE=Coverage # Test debug build and coverage options
  - cmake --build coveragebuild
  - ./coveragebuild/oatest/oatest
  - ./coveragebuild/oalhstest/oalhstest

after_success:
  - cd coveragebuild
  - lcov --directory oatest --directory oalhstest --capture --output-file oatest.info
  - lcov --remove oatest.info 'oatest/*' 'oalhstest/*' '/usr/*' --output-file oatest.clean.info
  - lcov --list oatest.clean.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

