language: cpp

dist: xenial
sudo: false

addons:
  apt:
    packages:
      - lcov
      - cmake
      - valgrind

jobs:
  include:
    - script:
      - cd src
      - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Debug
      - cmake --build build
      - valgrind ./build/oatest/oatest
      - valgrind ./build/oalhstest/oalhstest
    - script:
      - cd src
      - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release # Test release build options
      - cmake --build build
      - ./build/oatest/oatest
      - ./build/oalhstest/oalhstest
    - script:
      - cd src
      - cmake . -Bcoveragebuild -DCMAKE_BUILD_TYPE=Coverage # Test debug build and coverage options
      - cmake --build coveragebuild
      - ./coveragebuild/oatest/oatest
      - ./coveragebuild/oalhstest/oalhstest
      after_success:
      - cd coveragebuild
      - lcov --directory oatest --directory oalhstest --capture --output-file oatest.info
      - lcov --remove oatest.info 'oatest/*' 'oalhstest/*' '/usr/*' --output-file oatest.clean.info
      - lcov --list oatest.clean.info
      - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
