language: c++

dist: trusty
sudo: false

# Environment variables
env:
  global:
    - GH_REPO_NAME: oa
    - DOXYFILE: doxygen.config
    - GH_REPO_REF: github.com/bertcarnell/oa.git

addons:
  apt:
    packages:
      - lcov
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - cd src
  - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release # Test release build options
  - cmake --build build
  - ./build/oatest/oatest
  - ./build/oalhstest/oalhstest
  - cmake . -Bcoveragebuild -DCMAKE_BUILD_TYPE=Coverage # Test debug build and coverage options
  - cmake --build coveragebuild
  - ./coveragebuild/oatest/oatest
  - ./coveragebuild/oalhstest/oalhstest

after_success:
  - cd coveragebuild
  - lcov --directory oatest --directory oalhstest --capture --output-file oatest.info
  - lcov --remove oatest.info 'oatest/*' 'oalhstest/*' '/usr/*' --output-file oatest.clean.info
  - lcov --list oatest.clean.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
