language: c++

dist: trusty
sudo: false

#https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#  {
#    "alias": "r-packages-trusty",
#    "sourceline": "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/",
#    "key_url": "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x51716619E084DAB9"
#  },

addons:
  apt:
    sources:
      - r-packages-trusty
    packages:
      - lcov
      - r-base
      - r-base-dev
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

install:
  - sudo R --slave --vanilla -e "install.packages('Rcpp', repos='http://cran.case.edu')"

script:
  - cd oa_nb
  - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release # Test release build options
  - cmake --build build
  - ./build/oatest/oatest
  - ./build/oalhstest/oalhstest
  - cmake . -Bcoveragebuild -DCMAKE_BUILD_TYPE=Coverage # Test debug build and coverage options
  - cmake --build coveragebuild
  - ./coveragebuild/oatest/oatest
  - ./coveragebuild/oalhstest/oalhstest

after_success:
  - cd coveragebuild
  - lcov --directory oatest --directory oalhstest --capture --output-file oatest.info
  - lcov --remove oatest.info 'oatest/*' 'oalhstest/*' '/usr/*' --output-file oatest.clean.info
  - lcov --list oatest.clean.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  - cd $TRAVIS_BUILD_DIR/oa_nb
  - doxygen doxygen.config
  - git add --all
  - git commit -m "Documentation Travis build: $TRAVIS_BUILD_NUMBER with commit: $TRAVIS_COMMIT"

#  - git push --force "https://${GH_REPO_TOKEN}@${GH_REPO_REF}" > /dev/null
