name: CppLinter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Packages
        run: sudo apt-get install clang clang-tidy cppcheck

      - name: Run checks
        run: |
          clang-tidy --version
          clang-tidy *.cpp -checks=boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-cplusplus-*,clang-analyzer-*,cppcoreguidelines-* > clang-tidy-report.txt
          cppcheck --enable=all --std=c++11 --language=c++ --output-file=cppcheck-report.txt *

      - name: Archive clang tidy artifacts
        uses: actions/upload-artifact@v2
        with:
          name: clang-tidy-output
          path: clang-tidy-report.txt

      - name: Archive cppchekc artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck-output
          path: cppcheck-report.txt
